### ISSUE TITLE
Using an `alpine` docker image causes package imports to fail

### ISSUE THREAD

**Issue by morgs208** [amplitude/experiment-python-server#49]
## Expected Behavior
Application builds and installs all amplitude experiment packages

## Current Behavior

Application using an `alpine` image fails to load:
`File "/usr/local/lib/python3.11/site-packages/amplitude_experiment/local/evaluation/libevaluation_interop.py", line 548, in __call__
    raise ImportError("Could not load %s." % libname)
ImportError: Could not load libevaluation_interop.`

## Possible Solution
Changing the docker image to a `debian` image, fixed the issue:

* initial `alpine` image:  `python:3.11-alpine`

* `debian` image that worked: `python:3.11-slim-bullseye`

## Environment
- SDK Version: 
- Language Version: Python 3.11

**Comment by bgiori** [comment]
Hey @morgs208, Thanks for submitting this issue. 

The SDK currently does not support alpine linux due to a shared binary that is used to implement the core evaluation logic that is built expecting glibc rather than muslc (used by alpine images).

We plan to support alpine once the core evaluation logic is transcribed to python. (currently the only two holdouts still using the binary are python and ruby).

I'll keep this issue open until we add support. Thanks for your patience.

Brian

**Comment by bgiori** [comment]
Hi @morgs208 this should be fixed in v1.6.0

We have reimplemented completely in python, so we should now support `alpine` containers (muslc)
